In [3]:
import os
os.chdir('/home/brian/Documents/CPS/data/clean/')

In [33]:
import pandas as pd
import numpy as np
import itertools
import datetime as dt1
import matplotlib as mpl
import matplotlib.pyplot as plt
import wquantiles

age_tuple = (18, 64)
path_feather = ''

# Age and sex demographics in March 2001
filter_cols = ['AGE','BASICWGT', 'MONTH','IND03D','OCC03M','HRSUSL1','WORKFT', 'USLFT', 'PWORWGT','HRWAGE', 'PRICEADJ']

# Python function returns percentile using interpolation
def binned_wage2(df, wage_var='HRWAGE', perc=0.5, 
                bins=np.arange(-0.25, 300, 0.5)):
    '''
    Returns wage estimate based on linear interpolation through 
    the bin containing the wage.
    
    perc = percentile of interest (0.5 is median)
    bins = list of bin start locations
    '''
    cdf = (df.groupby(pd.cut(df[wage_var], bins))
             .PWORWGT.sum().cumsum() / df.PWORWGT.sum())
    
    return np.interp(perc, cdf, bins[1:])

rhrwage = lambda x: x.HRWAGE * x.PRICEADJ

ind_dict={'Agriculture':1,
 'Forestry_logging':2,
 'Mining':3,
 'Construction':4}

occ_dict={'prodn_occpn':9,'sales_related_occpn':4}
ind_occ_list=list(itertools.product(list(ind_dict.keys()),list(occ_dict.keys())))
results = {}
for idx,val in enumerate(ind_occ_list):
    results[val[0]]={}
    results[val[0]][val[1]]=pd.DataFrame()
    for year in range(2019, 2021):
        annual_data = (pd.read_feather(f'{path_feather}//cps{year}.ft', columns=filter_cols)
                        .query(f'{age_tuple[0]} <= AGE <= {age_tuple[1]} and HRSUSL1 >= 35 and OCC03M == 9 and HRWAGE > 0 and WORKFT == 1 and PWORWGT > 0 and IND03D == {ind_dict[val[0]]}')
                        .assign(RHRWAGE = rhrwage))
        for month, df in annual_data.groupby('MONTH'):
            # df=annual_data.query(f"'MONTH'=={month}")        
            date = pd.to_datetime(f'{year}-{month}-01')
            results[val[0]][val[1]].at[date, 'wq_wage'] = wquantiles.median(df['HRWAGE'], df['PWORWGT'])
            results[val[0]][val[1]].at[date, 'bw'] = binned_wage2(df)

In [34]:
results

{'Agriculture': {'sales_related_occpn':               wq_wage         bw
  2019-01-01  19.020000  19.000000
  2019-02-01   7.211500   7.000000
  2019-03-01  16.259642  17.924459
  2019-04-01  16.565003  15.191605
  2019-05-01  16.000000  16.031366
  2019-06-01  23.059999  23.000000
  2019-07-01  42.000000  42.000000
  2019-08-01  15.588489  15.825183
  2019-11-01  17.000000  17.000000
  2019-12-01  16.965986  16.212837
  2020-01-01  12.000000  12.000000
  2020-02-01  24.839750  25.000000
  2020-03-01  21.500000  21.500000
  2020-04-01  16.220330  16.783271
  2020-05-01  13.490110  12.185347
  2020-06-01  16.850000  17.000000
  2020-07-01  16.698788  16.793628
  2020-08-01  14.185547  15.792685
  2020-11-01  19.446164  19.058897
  2020-12-01  14.000000  14.000000},
 'Forestry_logging': {'sales_related_occpn':               wq_wage         bw
  2019-04-01  12.449462   1.655970
  2019-05-01  18.500000  18.500000
  2019-06-01  20.539100  20.049289
  2019-08-01  23.332766  27.388371
  2019-09-01  18.000000  18.000000
  2019-10-01  25.000000  25.000000
  2019-11-01  22.000000  22.000000
  2020-01-01  17.836443  16.232866
  2020-02-01   8.000000   8.000000
  2020-03-01  34.599998  34.500000
  2020-04-01  23.244269  23.023035
  2020-06-01  12.593093  12.645117
  2020-07-01  18.500000  18.500000
  2020-08-01  20.293141  18.154655
  2020-09-01  13.000000  13.000000
  2020-10-01  15.000000  15.000000
  2020-11-01  19.080000  19.000000},
 'Mining': {'sales_related_occpn':               wq_wage         bw
  2019-01-01  41.199136  52.750461
  2019-02-01  22.303229  22.959520
  2019-03-01  34.686486  34.740649
  2019-04-01  17.151307  17.907419
  2019-05-01  17.000000  17.000000
  2019-06-01  13.143558  13.026459
  2019-07-01  16.301859  16.494935
  2019-08-01  20.696978  20.602178
  2019-09-01  17.000000  17.000000
  2019-10-01  21.400497  21.357583
  2019-11-01  23.225391  23.896334
  2019-12-01  51.054012  59.806005
  2020-01-01  19.229759  19.752783
  2020-02-01  21.012879  22.797509
  2020-03-01  23.379470  23.896813
  2020-04-01  26.942597  28.884404
  2020-05-01  21.816771  21.964364
  2020-06-01  22.098023  22.080757
  2020-07-01  20.199880  20.113441
  2020-08-01  17.029528  18.887609
  2020-09-01  26.401277  28.768507
  2020-10-01  23.536002  23.540163
  2020-11-01  21.553099  20.198454
  2020-12-01  31.299098  28.194922},
 'Construction': {'sales_related_occpn':               wq_wage         bw
  2019-01-01  16.500000  16.650564
  2019-02-01  16.116426  16.119574
  2019-03-01  20.996488  20.965999
  2019-04-01  20.381324  20.228640
  2019-05-01  19.443874  18.231327
  2019-06-01  15.000000  15.091411
  2019-07-01  20.400715  20.942000
  2019-08-01  17.335797  17.531088
  2019-09-01  16.980865  16.579821
  2019-10-01  23.603595  26.282357
  2019-11-01  20.958801  20.852415
  2019-12-01  15.951303  15.929130
  2020-01-01  20.944416  20.139497
  2020-02-01  21.161480  21.015488
  2020-03-01  21.673268  20.142470
  2020-04-01  26.202610  26.194914
  2020-05-01  19.917236  19.604956
  2020-06-01  14.663183  14.230381
  2020-07-01  35.117659  37.847443
  2020-08-01  17.579986  18.773411
  2020-09-01  23.766303  29.764785
  2020-10-01  18.436565  18.444733
  2020-11-01  25.271128  25.277243
  2020-12-01  17.822108  19.872629}}

In [8]:
df = pd.read_feather('cps2019.ft')

In [9]:
for key in df.keys():
    print(key)

HHID
MONTH
YEAR
FAMINC
HHWGT
MIS
HHID2
CBSA
GTCBSASZ
CSA
PARENT
SPOUSE
PRDTRACE
LINENO
FAMNUM
PRFAMREL
HRSUSL1
HRSUSL2
HRSUSLT
HRSACT1
HRSACT2
HRSACTT
UNEMPDUR
PRWKSTAT
PRAGNA
IND03D
IND203D
OCC03D
OCC203D
IND03M
IND203M
OCC03M
OCC203M
PTWK
PWFMWGT
PWLGWGT
PWORWGT
PWSSWGT
PRCHLD
PRNMCHLD
WKEARNFLG
QSTNUM
OCCURNUM
BASICWGT
IND12
OCC10
IND212
OCC210
AGE
FEMALE
STATE
REGION
EDUCDT
EDUC
SCHENR
SCHOOL
RETIRED
MARRIED
WBHAO
WBAO
HISPANIC
VETERAN
FORBORN
CITIZEN
UNEMPTYPE
JLTYPE
LAYOFF
PTECON
USLFT
WORKFT
FTLF
SAMEEMP
CHDUTIES
SAMEACT
CHJOBACT
NOTATWORK
ABSTYPE
ABSPAID
PTREASON
WANTFT
DWTYPE
PAIDHRLY
PROXY
LFS
COW1
COW2
INDGRP
MANAGER
MJH
NUMJOBS
NILFREASON
NLFFAM
WKEARN
HRWAGE
OTCAMT
PRICEADJ
MINWAGE
CTYBIRTH
WBHAOM
HISPDT03
HISPDT
ATLFLG
INDM
ASIANDT
CERT
DISABILITY
CPSID
COUNTY
METSTAT
MPCSTAT
WKEARNADJ
HRSUSL1I
HRWAGEADJ
UNION
UNIONMEM

In [28]:
df.query('USLFT == -4')

Empty DataFrame
Columns: [AGE, BASICWGT, MONTH, IND03D, OCC03M, HRSUSL1, WORKFT, USLFT, PWORWGT, HRWAGE]
Index: []